name: generate plantuml

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: install puml generator
        run: dotnet tool install --global PlantUmlClassDiagramGenerator

      - name: generate puml from C#
        run: |
          puml-gen . -o diagrams

      - name: render plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: diagrams
          message: "Auto-generate UML from C#"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
